[tool.poetry]
name = "github-action"
version = "0.1.0"
description = ""
authors = ["Nikos Petalidis <nikos@petalidis.gr>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
