name: Test Action
on: [push]

jobs:
  get-num-square:
    runs-on: self-hosted
    name: Returns some info
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Fetch latest
        id: get_something
        uses: ./
        with: 
          name: 'myname'
      - name: Print the square
        run: echo ${{ steps.get_something.outputs.project_id }}
        shell: bash