name: Test Action
on: [push]

jobs:
  get-num-square:
    runs-on: self-hosted
    name: Returns some info
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: build staking
        run: |
            cd staking-v0.1
            pnpm install
            cd -
        shell: bash
      - name: Fetch latest
        id: get_something
        uses: ./
        with: 
          name: 'myname'
          init: true
          api-key: '4b69375c6e2301b5b429c7db2f4f4513a906f9d655493d10b6aeba6c66087f8727851e6abf05b4a97cc8165e8f367ec15f643e3d4b628457a3e6ff7aef8e7e96'
          framework: 'Hardhat'
          location: staking-v0.1
      - name: Print the info
        run: |
          echo ${{ steps.get_something.outputs.project_id }}
          echo ${{ steps.get_something.outputs.version_id }}

        shell: bash