name: Test Action
on: [push]

jobs:
  get-num-square:
    runs-on: self-hosted
    name: Returns some info
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Fetch latest
        id: get_something
        uses: ./ # Uses an action in the root directory
        # or use a released GitHub Action
        # uses: shipyard/github-action/fetch-shipyard-env@1.0.0
        with: 
          name: 'myname'
        run: echo ${{ steps.get_something.outputs.project_id }}
        shell: bash