name: Demo Dedaub github actions
on: [push]

jobs:
  staging-build:
    runs-on: self-hosted
    name: Analyse staking v-0.1
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: build staking
        run: |
            cd staking-v0.1
            echo "MNEMONIC=one two three four five six seven eight nine ten eleven twelve" > .env
            echo "VIA_IR=true" >> .env
            pnpm install
            pnpm compile
            cd -
        shell: bash
      - name: Run srcup
        id: srcup
        uses: dedaub/srcup-ci-action@v0.0.1
        with: 
          name: 'myname-a6'
          api-key: ${{ secrets.WATCHDOG_SECRET }}
          framework: 'Hardhat'
          location: staking-v0.1
      - name: Get analysis summary
        id: get_project_report
        uses: dedaub/srcwarnings-ci-action@v0.0.1
        with:
          project-id: ${{ steps.srcup.outputs.project_id }}
          version-id: ${{ steps.srcup.outputs.version_id }}
          api-key: ${{ secrets.WATCHDOG_SECRET }}
          api-url: 'http://localhost:8000/api'
      - name: Print the info
        run: | 
          echo ${{ steps.get_project_report.outputs.project_report }}
          echo ${{ steps.get_project_report.outputs.project_report }} >> $GITHUB_STEP_SUMMARY
        shell: bash