name: Test Action
on: [push]

jobs:
  get-num-square:
    runs-on: self-hosted
    name: Returns some info
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: build staking
        run: |
            cd staking-v0.1
            echo "MNEMONIC=one two three four five six seven eight nine ten eleven twelve" > .env
            echo "VIA_IR=true" >> .env
            pnpm install
            pnpm compile
            cd -
        shell: bash
      - name: Fetch latest
        id: get_something
        uses: npetalid/srcup-ci-action@v0.0.3
        with: 
          name: 'myname-a4'
          init: true
          api-key: ${{ secrets.WATCHDOG_SECRET }}
          framework: 'Hardhat'
          location: staking-v0.1
      - name: Fetch latest
        id: get_project_report
        uses: npetalid/srcwarnings-ci-action@v0.0.3
        with:
          project-id: ${{ steps.get_something.outputs.project_id }}
          version-id: ${{ steps.get_something.outputs.version_id }}
          api-key: ${{ secrets.WATCHDOG_SECRET }}
      - name: Print the info
        run: |
          echo ${{ steps.get_project_report.outputs.project_report }}
          echo ${{ steps.get_project_report.outputs.project_report }} >> $GITHUB_STEP_SUMMARY
          echo "Finished"
        shell: bash