name: Test Action
on: [push]

jobs:
  get-num-square:
    runs-on: self-hosted
    name: Returns some info
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: build staking
        run: |
            cd staking-v0.1
            echo "MNEMONIC=one two three four five six seven eight nine ten eleven twelve" > .env
            echo "VIA_IR=true" >> .env
            pnpm install
            pnpm compile
            cd -
        shell: bash
      - name: Fetch latest
        id: get_something
        uses: npetalid/srcup-ci-action@v0.0.2
        with: 
          name: 'myname-a1'
          init: true
          api-key: ${{ secrets.WATCHDOG_SECRET }}
          framework: 'Hardhat'
          location: staking-v0.1
      - name: Print the info
        run: |
          echo ${{ steps.get_something.outputs.project_id }}
          echo ${{ steps.get_something.outputs.version_id }}
          echo "Finished"
        shell: bash